 #kafka  binder topic name 
 
spring:
  cloud:
    stream:
      bindings:        output:
          content-type: application/json
          destination: user-stream 
        input : 
          content-type: application/json  datasource:    url: jdbc:mysql://192.168.1.164:3306/kings
    username: kings
    password: kings@123
  jpa:    show-sql: true
        